# prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Añadir más configuraciones de scrape aquí para otros servicios o exporters
  - job_name: 'sonarqube'
    scrape_interval: 1m
    scrape_timeout: 30s
    metrics_path: '/api/prometheus/metrics'
    static_configs:
    - targets: ['sonarqube:9000']
    basic_auth:
      username: '${PROMETHEUS_USERNAME}'
      password: '${PROMETHEUS_PASSWORD}'